name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install and build frontend
      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: npm run build

      # Install and build functions
      - name: Install functions dependencies
        working-directory: ./functions
        run: |
          npm ci
          npm run build || echo "no build step in functions"

      # Authenticate to Firebase
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PINGPONG2S }}

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      # Deploy hosting + functions without lint
      - name: Deploy to Firebase (skip lint)
        env:
          FIREBASE_PROJECT: pingpong2s
          FUNCTIONS_EMULATOR: "false"
        run: |
          # Override predeploy hooks to skip lint
          firebase functions:config:get || true
          firebase deploy --only hosting,functions --project "$FIREBASE_PROJECT" --ignore-predeploy-hooks
