name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install and build frontend
      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: npm run build

      # Install functions dependencies
      - name: Install functions dependencies
        run: |
          cd functions
          npm install
          npm run build

      # Deploy hosting + functions
      - name: Deploy to Firebase Hosting and Functions
        uses: w9jds/firebase-action@v13
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PINGPONG2S }}
          PROJECT_ID: pingpong2s
